### ISSUE TITLE
Truffle 5.0.1 (or possibly before) introduces breaking changes.

### ISSUE THREAD

**Issue by Freydal** [zulhfreelancer/truffle-events#1]
I just updated truffle, zeppelin and others now that they are supporting solc 0.5.0.  I found that the test cases using this library were failing.  I found that the transaction result.receipt.logs was empty and seem to have been moved to rawLogs.  I suspect the logs array is reserved for logs decoded by truffle for the specific contract.  

I thought I would bring it up in case you plan on maintaining this library.

**Comment by zulhfreelancer** [comment]
Thanks @Freydal. I'm double checking something in this PR https://github.com/zulhfreelancer/truffle-events/pull/2.
